import "./globals.css";
import 'leaflet/dist/leaflet.css';
import { Toaster } from "react-hot-toast";
import RootLayoutClient from "./RootLayoutClient";
import { Inter, Poltawski_Nowy } from 'next/font/google'


const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

const poltawski = Poltawski_Nowy({
  subsets: ['latin'],
  variable: '--font-poltawski',
})

export const metadata = {
  title: "LAEatery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster
          position="top-center"
          reverseOrder={false}
        />
            <div className={`${inter.variable} ${poltawski.variable}`}>
              <RootLayoutClient>{children}</RootLayoutClient>
            </div>
      </body>
    </html>
  );
}
